apiVersion: v1
kind: Service
metadata:
  name: kv
  namespace: helix
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: kv
  ports:
    - name: client
      port: 8000
    - name: raft
      port: 7000
